# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/payment/payment.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto/payment/payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproto/payment/payment.proto\x12\x07payment\"I\n\x15ProcessPaymentRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\t\x12\x0e\n\x06method\x18\x03 \x01(\t\"^\n\x16ProcessPaymentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\npayment_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"+\n\x17GetPaymentStatusRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"p\n\x18GetPaymentStatusResponse\x12\x12\n\npayment_id\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\t\x12\x0e\n\x06method\x18\x05 \x01(\t2\xbc\x01\n\x0ePaymentService\x12Q\n\x0eProcessPayment\x12\x1e.payment.ProcessPaymentRequest\x1a\x1f.payment.ProcessPaymentResponse\x12W\n\x10GetPaymentStatus\x12 .payment.GetPaymentStatusRequest\x1a!.payment.GetPaymentStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.payment.payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESSPAYMENTREQUEST']._serialized_start=40
  _globals['_PROCESSPAYMENTREQUEST']._serialized_end=113
  _globals['_PROCESSPAYMENTRESPONSE']._serialized_start=115
  _globals['_PROCESSPAYMENTRESPONSE']._serialized_end=209
  _globals['_GETPAYMENTSTATUSREQUEST']._serialized_start=211
  _globals['_GETPAYMENTSTATUSREQUEST']._serialized_end=254
  _globals['_GETPAYMENTSTATUSRESPONSE']._serialized_start=256
  _globals['_GETPAYMENTSTATUSRESPONSE']._serialized_end=368
  _globals['_PAYMENTSERVICE']._serialized_start=371
  _globals['_PAYMENTSERVICE']._serialized_end=559
# @@protoc_insertion_point(module_scope)
